### ISSUE TITLE
fedora 29 dnf  system-upgrade

### ISSUE THREAD

**Issue by antivir88** [rpm-software-management/dnf-plugins-extras#167] opened 2019-10-31 10:39 UTC
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 115, in cli_run
    cli.run()
  File "/usr/lib/python3.7/site-packages/dnf/cli/cli.py", line 1055, in run
    return self.command.run()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/system_upgrade.py", line 322, in run
    self._call_sub("run")
  File "/usr/lib/python3.7/site-packages/dnf-plugins/system_upgrade.py", line 330, in _call_sub
    subfunc()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/system_upgrade.py", line 465, in run_download
    state.destdir = self.base.conf.destdir
  File "/usr/lib/python3.7/site-packages/dnf-plugins/system_upgrade.py", line 135, in __exit__
    self.write()
  File "/usr/lib/python3.7/site-packages/dnf-plugins/system_upgrade.py", line 123, in write
    json.dump(self._data, outf)
  File "/usr/lib64/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib64/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type VectorString is not JSON serializable

**Comment by m-blaha** [comment] 2019-11-04 07:59
Please, what is the version of system-upgrade plugin you are using?
``$ rpm -q python3-dnf-plugin-system-upgrade``
There were similar bugs https://bugzilla.redhat.com/show_bug.cgi?id=1649745 and https://bugzilla.redhat.com/show_bug.cgi?id=1643551 and both of them should be fixed in F29.

**Comment by antivir88** [comment] 2019-11-05 07:28
python3-dnf-plugin-system-upgrade-3.0.2-1.fc29.noarch

**Comment by m-blaha** [comment] 2019-11-05 08:27
You should be able to upgrade to 4.0.7-2.fc29 version from the Fedora 29 - Updates repo. I believe this version has the issue fixed.

**Comment by pkratoch** [comment] 2020-03-18 10:42
This looks like resolved, so I am closing it. If you can still reproduce the issue, please don't hesitate to reopen it.

**Closed by pkratoch** 2020-03-18 10:42 UTC
